project:
  type: website
  output-dir: docs

website:
  title: "Personal Analyses & Visualizations"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jackfay7/DataVizBlog
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cerulean
    css: styles.css



